export default {
    REGISTER_GROUP: 'REGISTER_GROUP',
    REGISTER_ITEM: 'REGISTER_ITEM',
    CLEAR_REGISTERED_GROUP: 'CLEAR_REGISTERED_GROUP',
    SET_DRAGGING_ITEM: 'SET_DRAGGING_ITEM',
    DROP_IN_GROUP: 'DROP_IN_GROUP',
}